# Generated by Django 5.1.7 on 2025-05-18 12:45

import django.db.models.deletion
import django.utils.timezone
import django_mysql.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('count_rooms', models.IntegerField()),
                ('CSI', models.FloatField()),
                ('stars', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('img1', django_mysql.models.SizedTextField(size_class=3)),
                ('img2', django_mysql.models.SizedTextField(size_class=3)),
                ('img3', django_mysql.models.SizedTextField(size_class=3)),
                ('img4', django_mysql.models.SizedTextField(size_class=3)),
                ('img5', django_mysql.models.SizedTextField(size_class=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_people', models.IntegerField()),
                ('arrival', models.DateTimeField()),
                ('departure', models.DateTimeField()),
                ('price_per_room', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('validity_period', models.DateField()),
                ('CVV', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pols.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favorites_hotel',
            field=models.ManyToManyField(through='pols.Favorites', to='pols.hotel'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('location', models.IntegerField()),
                ('сleanliness', models.IntegerField()),
                ('price_quality', models.IntegerField()),
                ('service', models.IntegerField()),
                ('wifi', models.IntegerField()),
                ('comments', models.TextField(null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pols.booking')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pols.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('beds_amount', models.IntegerField()),
                ('bath_amount', models.IntegerField()),
                ('s', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img1', django_mysql.models.SizedTextField(null=True, size_class=3)),
                ('img2', django_mysql.models.SizedTextField(null=True, size_class=3)),
                ('img3', django_mysql.models.SizedTextField(null=True, size_class=3)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pols.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('rooms', models.ManyToManyField(to='pols.rooms')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pols.rooms'),
        ),
    ]
