# Generated by Django 5.1.7 on 2025-05-09 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('location', models.IntegerField()),
                ('сleanliness', models.IntegerField()),
                ('price_quality', models.IntegerField()),
                ('service', models.IntegerField()),
                ('wifi', models.IntegerField()),
                ('comments', models.TextField(null=True)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pols.booking')),
            ],
        ),
    ]
